import Papa from 'papaparse';
import { AccountDetails, Transaction } from '../types';

export function generateAxisCSV(transactions: Transaction[], accountDetails: AccountDetails): string {
  const headerRows = [
    [`Name :- ${accountDetails.name}`, '', '', '', '', '', '', '', '', '', ''],
    [`Joint Holder :- ${accountDetails.jointHolder}`, '', '', '', '', '', '', '', '', '', ''],
    [`C/O ${accountDetails.address1}`, '', '', '', '', '', '', '', '', '', ''],
    [`${accountDetails.address2}`, '', '', '', '', '', '', '', '', '', ''],
    [`${accountDetails.address3}`, '', '', '', '', '', '', '', '', '', ''],
    [`${accountDetails.address4}`, '', '', '', '', '', '', '', '', '', ''],
    [`Customer ID :- ${accountDetails.customerId}`, '', '', '', '', '', '', '', '', '', ''],
    [`IFSC Code :- ${accountDetails.ifsc}`, '', '', '', '', '', '', '', '', '', ''],
    [`MICR Code :- ${accountDetails.micr}`, '', '', '', '', '', '', '', '', '', ''],
    [`Nominee Registered :- ${accountDetails.nomineeReg}`, '', '', '', '', '', '', '', '', '', ''],
    [`Nominee Name :- ${accountDetails.nomineeName}`, '', '', '', '', '', '', '', '', '', ''],
    [`Registered Mobile No :- ${accountDetails.mobile}`, '', '', '', '', '', '', '', '', '', ''],
    [`Registered Email ID :- ${accountDetails.email}`, '', '', '', '', '', '', '', '', '', ''],
    [`PAN :- ${accountDetails.pan}`, '', '', '', '', '', '', '', '', '', ''],
    [`CKYC NUMBER :- ${accountDetails.ckyc}`, '', '', '', '', '', '', '', '', '', ''],
    [`Statement of Account No - ${accountDetails.accountNo} for the period (From : ${accountDetails.fromDate} To : ${accountDetails.toDate})`, '', '', '', '', '', '', '', '', '', ''],
    ['\t', '', '', '', '', '', '', '', '', '', ''],
    ['SRL NO', 'Tran Date', 'CHQNO', 'PARTICULARS', 'DR', 'CR', 'BAL', 'SOL', '', '', '']
  ];

  const transactionRows = transactions.map((t, i) => [
    (i + 1).toString(),
    t.date,
    t.chqNo || '-',
    t.particulars,
    t.dr ? t.dr : ' ',
    t.cr ? t.cr : ' ',
    t.bal,
    t.sol || '100',
    '', '', ''
  ]);

  const footerRows = [
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['', '', '', '', '', '', '', '', '', '', ''],
    ['\t', '', '', '', '', '', '', '', '', '', ''],
    ['Unless the constituent notifies the bank immediately of any discrepancy found by him/her in this statement of Account, it will be taken that he/she has found the account correct.', '', '', '', '', '', '', '', '', '', ''],
    ['The closing balance as shown/displayed includes not only the credit balance and / or overdraft limit, but also funds which are under clearing. It excludes the amount marked as lien, if any. Hence the closing balance displayed may not be the effective available balance. For any further clarifications, please contact the Branch.', '', '', '', '', '', '', '', '', '', ''],
    ['We would like to reiterate that, as a policy, Axis Bank never asks you to share, disclose, or revalidate your login Id, password or debit card number  number through emails OR phone call Further,we would like to reiterate that Axis Bank shall not be liable for any losses arising from you sharing/disclosing of your login id, password and debit card number to anyone. Please co-operate by forwarding all such suspicious/spam emails, if received by you, to customer.service@axis.bank.in', '', '', '', '', '', '', '', '', '', ''],
    ['With effect from 1st August 2016, the replacement charges for Debit card and ATM card applicable on Current accounts have been revised. To know more about the applicable charges,please visit www.axis.bank.in', '', '', '', '', '', '', '', '', '', ''],
    ['Deposit Insurance and Credit Guarantee Corporation (DICGC) insurance cover is applicable in all Bank\'s deposits, such as savings, current, fixed, recurring etc.* up to maximum amount of Rs 5 Lakh including principal &interest both* (*for exceptions and details please refer http://www.dicgc.org.in/ )', '', '', '', '', '', '', '', '', '', ''],
    ['In compliance with regulatory guidelines, the non-CTS cheque books attached to the accounts would be destroyed in banks core banking System. Thus, Non CTS cheques will not be valid for CASH, Clearing and Transfer transactions', '', '', '', '', '', '', '', '', '', ''],
    ['To ensure you never miss any critical communication from us, it is important that your latest / correct mobile number and email ID are updated in our records. Kindly visit your nearest Axis Bank Loan Centre /Branch / Agri area office for updating your latest / correct mobile number and email ID in our records. You can also update your email ID using Internet Banking & Mobile Banking App, open', '', '', '', '', '', '', '', '', '', ''],
    ['REGISTERED OFFICE - AXIS BANK LTD,TRISHUL,Opp. Samartheswar Temple, Near Law Garden, Ellisbridge, Ahmedabad . 380006.', '', '', '', '', '', '', '', '', '', ''],
    ['BRANCH ADDRESS - AXIS BANK LTD, BATIAHATA BRANCH (UP), GF HNO.002 BATIAHATA GORAKHPUR, TEHSIL SADAR,  ,  273001,  GORAKHPUR,  UTTAR PRADESH, INDIA, TEL:7310333732  FAX:', '', '', '', '', '', '', '', '', '', ''],
    ['\t', '', '', '', '', '', '', '', '', '', ''],
    ['Legend :', '', '', '', '', '', '', '', '', '', ''],
    ['ICONN\t\t\t-\t\t\tTransaction trough Internet Banking', '', '', '', '', '', '', '', '', '', ''],
    ['VMT-ICON\t\t-\t\t\tVisa Money Transfer through Internet Banking', '', '', '', '', '', '', '', '', '', ''],
    ['AUTOSWEEP \t\t-\t\t\tTransfer to linked fixed deposit', '', '', '', '', '', '', '', '', '', ''],
    ['REV SWEEP \t\t-\t\t\tInterest on Linked fixed Deposit', '', '', '', '', '', '', '', '', '', ''],
    ['SWEEP TRF\t\t-\t\t\tTransfer from Linked Fixed Deposit / Account', '', '', '', '', '', '', '', '', '', ''],
    ['VMT\t\t\t\t-\t\t\tVisa Money Transfer through ATM', '', '', '', '', '', '', '', '', '', ''],
    ['CWDR\t\t\t-\t\t\tCash Withdrawal through ATM', '', '', '', '', '', '', '', '', '', ''],
    ['PUR\t\t\t\t-\t\t\tPOS purchase', '', '', '', '', '', '', '', '', '', ''],
    ['TIP/ SCG\t\t-\t\t\tSurcharge on usage of debit card at pumps/railway ticket purchase or hotel tips', '', '', '', '', '', '', '', '', '', ''],
    ['RATE.DIFF\t\t-\t\t\tDifference in rates on usage of card internationally', '', '', '', '', '', '', '', '', '', ''],
    ['CLG\t\t\t-\t\t\tCheque Clearing Transaction', '', '', '', '', '', '', '', '', '', ''],
    ['EDC\t\t\t-\t\t\tCredit transaction through EDC Machine', '', '', '', '', '', '', '', '', '', ''],
    ['SETU\t\t\t-\t\t\tSeamless electronic fund transfer through AXIS Bank', '', '', '', '', '', '', '', '', '', ''],
    ['Int.pd\t\t\t-\t\t\tInterest paid to customer', '', '', '', '', '', '', '', '', '', ''],
    ['Int.Coll\t\t-\t\t\tInterest collected from the customer', '', '', '', '', '', '', '', '', '', ''],
    ['\t', '', '', '', '', '', '', '', '', '', ''],
    ['This is a system generated output and requires no signature.', '', '', '', '', '', '', '', '', '', '']
  ];

  const finalData = [...headerRows, ...transactionRows, ...footerRows];
  
  // Papa.unparse automatically handles quoting and escaping
  return Papa.unparse(finalData, {
    quotes: false, // Don't quote everything, only when necessary
    quoteChar: '"',
    escapeChar: '"',
    delimiter: ",",
    header: false,
    newline: "\r\n",
  });
}
